DROP TABLE if exists PRODUCTS, ORDER_ITEMS, ORDERS, CUSTOMER, DEPT, EMP;

CREATE TABLE CUSTOMER (
    CUSTOMER_NAME VARCHAR(30) NOT NULL,
    CUSTOMER_PHONE INT,
    CUSTOMER_ID INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ORDERS (
    ORDER_NUM INT AUTO_INCREMENT NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ORDER_PICK_UP_TIME TIME NOT NULL,
    ORDER_STATUS TINYINT,
    CUSTOMER_ID INT NOT NULL,
    TOTAL_PRICE DOUBLE NOT NULL,
    PRIMARY KEY (ORDER_NUM),
    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (CUSTOMER_ID)
);

CREATE TABLE PRODUCTS (
	PRODUCT_NUMBER INT UNIQUE NOT NULL,
    PRODUCT_ID INT AUTO_INCREMENT NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    TOPPINGS VARCHAR(100) NOT NULL,
    PRICE DOUBLE NOT NULL,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE ORDER_ITEMS (
    ORDER_NUM INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PRIMARY KEY (ORDER_NUM, PRODUCT_ID)
);

INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (1, 'Vesuvio', 'tomatsauce,ost,skinke,oregano', 57);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (2, 'Amerikaner', 'tomatsauce,ost,oksefars,oregano', 53);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (3, 'Cacciatore', 'tomatsauce,ost,pepperoni,oregano', 57);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (4, 'Carbona', 'tomatsauce,ost,kødsauce,spaghetti,cocktailpølser,oregano', 63);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (5, 'Dennis', 'tomatsauce,ost,skinke,pepperoni,cocktailpølser,oregano', 65);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (6, 'Bertil', 'tomatsauce,ost,bacon,oregano', 57);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (7, 'Silvia', 'tomatsauce,ost,pepperoni,rød,peber,løg,oliven,oregano', 61);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (8, 'Victoria', 'tomatsauce,ost,skinke,ananas,champignon,løg,oregano', 61);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (9, 'Toronto', 'tomatsauce,ost,skinke,bacon,kebab,chili,oregano', 61);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (10, 'Capricciosa', 'tomatsauce,ost,skinke,champignon,oregano', 61);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (11, 'Hawaii', 'tomatsauce,ost,skinke,ananas,oregano', 61);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (12, 'Le-Blissola', 'tomatsauce,ost,skinke,rejer,oregano', 61);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (13, 'Venezia', 'tomatsauce,ost,skinke,bacon,oregano', 61);
INSERT INTO PRODUCTS (PRODUCT_NUMBER, PRODUCT_NAME, TOPPINGS, PRICE) VALUES (14, 'Mafia', 'tomatsauce,ost,pepperoni,bacon,løg,oregano', 61);

SELECT 
    *
FROM
    PRODUCTS;
commit;
